# Generated by Django 4.1.3 on 2022-11-11 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_event_benefits_history_alter_appointment_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='day',
            new_name='creation_time',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='name',
            new_name='history_description',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='time',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='url',
            new_name='user_name',
        ),
    ]
